### ISSUE TITLE
Any references or comparisons of SSIM loss over MSE

### ISSUE THREAD

**Issue by anilrgukt** [mehtadushy/DeepNetStuff#1]
Dear Mehta,
   Do you have experiments showing the improvements SSIM loss over MSE? Anyways, thanks for sharing the loss layers in caffe. That will be of great help to me.

**Comment by mehtadushy** [comment]
This was used in our paper on [learned screen space shading](http://deep-shading-datasets.mpi-inf.mpg.de/)
You would find some comparisons in the paper and also in one of the references. Hope that helps
